# Generated by Django 5.0.7 on 2024-07-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
