# Generated by Django 5.0.7 on 2024-07-23 13:10

from django.db import migrations

def populate_image_field(apps, schema_editor):
    Image = apps.get_model('images', 'Image')
    for image in Image.objects.all():
        if image.image_path:
            image.image = image.image_path
            image.save()

def reverse_func(apps, schema_editor):
    # This is optional, but it's good practice to provide
    # a way to reverse the migration if needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_image'),
    ]

    operations = [
        migrations.RunPython(populate_image_field, reverse_func),
    ]
