# Generated by Django 5.0.7 on 2024-07-23 15:21

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_populate_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=images.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('cropped_IB', 'Western Blot'), ('cropped_IP', 'Immunoprecipitation')], max_length=10),
        ),
    ]
